'''
!/usr/bin/env python
-*- coding: utf-8 -*-
@Time    : 2025/7/15 17:47
@Author  : JunYU
@File    : main
'''

from fastapi import FastAPI
from endpoints import chemagent_chat
app = FastAPI(
    title="Chemistry Agent API, Generated by Jun YU",
    description="API for Chemistry",
    version="1.0.0",
)

app.include_router(chemagent_chat.router, prefix="/api/chemagent", tags=["Chemistry Agent"])

@app.get("/", tags=["Chemistry Agent"])
def read_root():
    return {"Hello": "World"}