"""Add steps field to messages table

Revision ID: eeaf213cd46c
Revises: 652dd7a2a40d
Create Date: 2025-07-27 16:07:15.380453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeaf213cd46c'
down_revision: Union[str, Sequence[str], None] = '652dd7a2a40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'steps')
    # ### end Alembic commands ###
